# Generated by Django 5.0.4 on 2024-05-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=None, max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default=None, max_length=150, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('SUPERMANAGER', 'supermanager'), ('MANAGER', 'manager'), ('DEALER', 'dealer'), ('CLIENT', 'client')], default='CLIENT', max_length=150, null=True, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'auth_user',
            },
        ),
    ]
