# Generated by Django 5.0.4 on 2024-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_role',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name=''),
        ),
    ]
