# Generated by Django 5.0.4 on 2024-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0002_customuser_sub_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clear_password',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
