# Generated by Django 5.0.4 on 2024-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0003_customuser_clear_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('owner', models.CharField(default=None, max_length=150, null=True, verbose_name='Владелец')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Имя'),
        ),
    ]
