# Generated by Django 5.0.4 on 2024-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0004_document_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=150, verbose_name='Название'),
        ),
    ]
