# Generated by Django 5.0.4 on 2024-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0007_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ip',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='IP'),
        ),
    ]
