# Generated by Django 5.0.4 on 2024-05-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0008_activity_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dealer_name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_role',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Задача'),
        ),
    ]
