# Generated by Django 5.0.4 on 2024-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0009_document_file_type_alter_customuser_dealer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Местоположение'),
        ),
    ]
