# Generated by Django 5.0.4 on 2024-05-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0013_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dealer_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_role',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Задача'),
        ),
    ]
