# Generated by Django 5.0.4 on 2024-05-16 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0015_folder_alter_customuser_clear_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents', verbose_name='Файл')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageDocumentreceiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageDocumentsender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Файл сообщения',
                'verbose_name_plural': 'Файлы сообщений',
            },
        ),
    ]
