# Generated by Django 4.2.9 on 2024-05-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0017_messagedocument_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Номенклатурв')),
                ('name', models.CharField(max_length=255, verbose_name='Ценовая группа/ Номенклатура/ Характеристика номенклатуры')),
                ('count', models.IntegerField(verbose_name='Остаток')),
                ('mark', models.CharField(max_length=255, verbose_name='Марка')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
