# Generated by Django 5.0.6 on 2024-06-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0021_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_parent_folder', to='sinotruk.folder'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('SUPERMANAGER', 'supermanager'), ('MANAGER', 'manager'), ('DEALER', 'DEALER'), ('CLIENT', 'client')], default='CLIENT', max_length=150, null=True, verbose_name='Роль'),
        ),
    ]
