# Generated by Django 5.0.6 on 2024-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0022_folder_parent_folder_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
