# Generated by Django 5.0.6 on 2024-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinotruk', '0023_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_emails',
            field=models.BooleanField(default=False, verbose_name='Разрешение на принятие заявок'),
        ),
    ]
